call_parentheses = "Always"
collapse_simple_statement = "Always"
column_width = 79
indent_type = "Spaces"
indent_width = 2
line_endings = "Unix"
remove_trailing_separators = false
quote_style = "AutoPreferDouble"
